# Travis CI build pipeline
# --------------------------------------------

os: linux
dist: xenial
language: csharp
solution: ExceptionLib.sln
mono: none
dotnet: 5.0.301

addons:
  apt:
    packages:
      - zip
      - tar
      - gzip

before_script:
  - set -e
  - dotnet restore

script:
  - |
    if [[ -z "$TRAVIS_TAG" ]]; then
      set -e
      dotnet build -c Release
      dotnet test /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:Exclude="[xunit*]*" /p:excludebyfile="**/*.Designer.cs"
      bash <(curl -s https://codecov.io/bash) -Z
    fi

before_deploy:
  - set -e
  - dotnet build ExceptionLib.sln -c Release
  - dotnet pack ExceptionLib.sln -c Release -o nuget
  - |
    mkdir output
    mv ./BaseExceptionLib/bin/Release ./output/BaseExceptionLib
  - |
    zip -r ./Exception.zip ./output/* 
    tar cfvz ./Exception.tar.gz ./output

deploy:
  provider: releases
  overwrite: true
  api_key: $GITHUB_TOKEN
  file:
    - "./Exception.zip"
    - "./Exception.tar.gz"
  skip_cleanup: true
  on:
    tags: true

after_deploy:
  - dotnet nuget push --skip-duplicate ./nuget/'*.nupkg' -k $NUGET_TOKEN -s https://api.nuget.org/v3/index.json
  - dotnet nuget push --skip-duplicate ./nuget/'*.nupkg' -k $PACKAGE_TOKEN -s https://nuget.pkg.github.com/sunriax/index.json